CanadaGames/Controllers/SportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CanadaGames.Data;
using CanadaGames.Models;
using CanadaGames.Utilities;
using CanadaGames.ViewModels;
using Microsoft.EntityFrameworkCore.Storage;

namespace CanadaGames.Controllers
{
    public class SportsController : Controller
    {
        private readonly CanadaGamesContext _context;

        public SportsController(CanadaGamesContext context)
        {
            _context = context;
        }

        // GET: Sports
        public async Task<IActionResult> Index(int? page, int? pageSizeID, string actionButton, string sortDirection = "asc", string sortField = "Sport")
        {
            string[] sortOptions = new[] { "Name" };

            var sports = from c in _context.Sports
                         .Include(c =>c.AthleteSports)
                         .ThenInclude(c => c.Athlete)
                          select c;

            if (!String.IsNullOrEmpty(actionButton)) //Form Submitted!
            {
                page = 1;//Reset page to start
            }

            //checking to see if there was a change in sorting
            if (!String.IsNullOrEmpty(actionButton))
            {
                if (sortOptions.Contains(actionButton))
                {
                    if (actionButton == sortField)
                    {
                        sortDirection = sortDirection == "asc" ? "desc" : "asc";
                    }
                    sortField = actionButton;
                }
            }
            //now the sort direction and field are known
            if (sortField == "Name")
            {
                if (sortDirection == "asc")
                {
                    sports = sports
                        .OrderByDescending(s => s.Name);
                }
                else
                {
                    sports = sports
                        .OrderBy(s => s.Name);
                }
            }

            ViewData["sortField"] = sortField;
            ViewData["sortDirection"] = sortDirection;

            int pageSize = PageSizeHelper.SetPageSize(HttpContext, pageSizeID);
            ViewData["pageSizeID"] = PageSizeHelper.PageSizeList(pageSize);
            var pagedData = await PaginatedList<Sport>.CreateAsync(sports.AsNoTracking(), page ?? 1, pageSize);

            return View(pagedData);
        }

        // GET: Sports/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sport = await _context.Sports
                .Include(c => c.AthleteSports)
                .ThenInclude(c => c.Athlete)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
            if (sport == null)
            {
                return NotFound();
            }

            return View(sport);
        }

        // GET: Sports/Create
        public IActionResult Create()
        {
            Sport sport = new Sport();
            PopulateAssignedSportData(sport);
            return View();
        }

        // POST: Sports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Code,Name")] Sport sport, string[] selectedOptions)
        {
            try
            {
                UpdateSports(selectedOptions, sport);
                if (ModelState.IsValid)
                {
                    _context.Add(sport);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Details", new { sport.ID});
                }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                ModelState.AddModelError("", "Unable to save changes after multiple attempts. Try again, and if the problem persists see your system administrator.");
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            PopulateAssignedSportData(sport);
            return View(sport);
        }

        // GET: Sports/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sport = await _context.Sports
                .Include(c => c.AthleteSports)
                .ThenInclude(c => c.Athlete)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (sport == null)
            {
                return NotFound();
            }

            PopulateAssignedSportData(sport);
            return View(sport);
        }

        // POST: Sports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Code,Name")] Sport sport, string[] selectedOptions)
        {
            var sportToUpdate = await _context.Sports
                .Include(c => c.AthleteSports)
                .ThenInclude(c => c.Athlete)
                .FirstOrDefaultAsync(m => m.ID == id);

            if (id != sport.ID)
            {
                return NotFound();
            }
            UpdateSports(selectedOptions, sportToUpdate);

            if (await TryUpdateModelAsync<Sport>(sport))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Details", new { sport.ID });
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    ModelState.AddModelError("", "Unable to save changes after multiple attempts. Try again, and if the problem persists see your system administrator.");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SportExists(sport.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }
            }
            PopulateAssignedSportData(sportToUpdate);
            return View(sportToUpdate);
        }

        // GET: Sports/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sport = await _context.Sports
                .Include(c => c.AthleteSports)
                .ThenInclude(c => c.Athlete)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
            if (sport == null)
            {
                return NotFound();
            }

            return View(sport);
        }

        // POST: Sports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sport = await _context.Sports
                .Include(c => c.AthleteSports)
                .ThenInclude(c => c.Athlete)
                .FirstOrDefaultAsync(m => m.ID == id);

            try
            {
                _context.Sports.Remove(sport);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException dex)
            {
                if (dex.GetBaseException().Message.Contains("FOREIGN KEY constraint failed"))
                {
                    ModelState.AddModelError("", "Unable to Delete Sport. Remember, you cannot delete a Sport with Athletes.");
                }
                else
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }
            }
            return View(sport);
        }

        private void PopulateAssignedSportData(Sport sport)
        {
            var allOptions = _context.Athletes;
            var currentOptionsHS = new HashSet<int>(sport.AthleteSports.Select(a => a.AthleteID));
            var selected = new List<ListOptionVM>();
            var available = new List<ListOptionVM>();
            foreach (var s in allOptions)
            {
                if (currentOptionsHS.Contains(s.ID))
                {
                    selected.Add(new ListOptionVM
                    {
                        ID = s.ID,
                        DisplayText = s.FullName
                    });
                }
                else
                {
                    available.Add(new ListOptionVM
                    {
                        ID = s.ID,
                        DisplayText = s.FullName
                    });
                }
            }

            ViewData["selOpts"] = new MultiSelectList(selected.OrderBy(s => s.DisplayText), "ID", "DisplayText");
            ViewData["availOpts"] = new MultiSelectList(available.OrderBy(s => s.DisplayText), "ID", "DisplayText");
        }
        private void UpdateSports(string[] selectedOptions, Sport athleteToUpdate)
        {

CanadaGames/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Canada Games 2022</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Images/n22-logo.svg" height="35" class="img-responsive" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Athletes" asp-action="Index">Athletes</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Games Menu<b class="caret"></b>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Coaches" asp-action="Index">Coaches</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="Sports" asp-action="Index">Sports</a>
                            </div>                            
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Canada Summer Games 2022- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CanadaGames/Views/Shared/_PageSizeModal.cshtml
<div class="modal fade" id="pageSizeModal" tabindex="-1" role="dialog" aria-labelledby="pageSizeModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="pageSizeModalLabel">Set Page Size</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Page Size: </span>
                            </div>
                            @Html.DropDownList("pageSizeID", null, htmlAttributes: new { @class = "form-control" })
                            <div class="input-group-append">
                                <input type="submit" class="btn btn-primary" value="Set Page Size" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CanadaGames/Views/Shared/_PagingNavBar.cshtml
<partial name="_PageSizeModal" />
@{
    if (Model.TotalPages == 1)
    {
        <ul class="pagination justify-content-center" style="margin:20px 0">
            <li class="page-item">
                <button type="button" title="Click to change page size." data-toggle="modal" data-target="#pageSizeModal" class="btn btn-primary">
                    Page @Model.PageIndex of @Model.TotalPages
                </button>
            </li>
        </ul>
    }
    else
    {
        var jumpAmount = (Model.TotalPages > 25) ? 10 : 5;
        var prevDisabled = !Model.HasPreviousPage ? "disabled='disabled'" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled='disabled'" : "";
        var stepBack = (Model.PageIndex <= jumpAmount) ? 1 : Model.PageIndex - jumpAmount;
        var stepForward = (Model.PageIndex + jumpAmount > Model.TotalPages) ? Model.TotalPages : Model.PageIndex + jumpAmount;
        <ul class="pagination justify-content-center" style="margin:20px 0">
            <li class="page-item">
                <button type="submit" name="page" value="1" @prevDisabled class="btn page-link">
                    <span aria-hidden="true">&lArr;</span>&nbsp;First
                </button>
            </li>
            <li class="page-item d-none d-md-inline">
                <button type="submit" name="page" value="@(stepBack)" @prevDisabled
                        data-toggle="tooltip" title="Jump Back @(Model.PageIndex-stepBack) Pages" class="btn page-link">
                    <span aria-hidden="true">&lArr;</span>
                </button>
            </li>
            <li class="page-item">
                <button type="submit" name="page" @prevDisabled value="@(Model.PageIndex - 1)" class="btn page-link">
                    &nbsp;<span aria-hidden="true">&larr;</span>&nbsp;<span class="d-none d-md-inline">Previous</span>
                </button>
            </li>
            <li class="page-item">
                <button type="button" title="Click to change page size." data-toggle="modal" data-target="#pageSizeModal" class="btn btn-primary">
                    <span class="d-none d-md-inline">Pg. </span>@Model.PageIndex of @Model.TotalPages
                </button>
            </li>
            <li class="page-item">
                <button type="submit" name="page" @nextDisabled value="@(Model.PageIndex + 1)" class="btn page-link">
                    <span class="d-none d-md-inline">Next</span>&nbsp;<span aria-hidden="true">&rarr;</span>&nbsp;
                </button>
            </li>
            <li class="page-item d-none d-md-inline">
                <button type="submit" name="page" @nextDisabled value="@(stepForward)" title="Jump Forward @(stepForward-Model.PageIndex) Pages" class="btn page-link">
                    <span aria-hidden="true">&rArr;</span>
                </button>
            </li>
            <li class="page-item">
                <button type="submit" name="page" @nextDisabled value="@(Model.TotalPages)" class="btn page-link">
                    Last&nbsp;<span aria-hidden="true">&rArr;</span>
                </button>
            </li>
        </ul>
    }
}